Add books components
KJP-Industries/can-of-books-frontend pull request #8
Opened 2023-08-16 05:33 UTC by easleyjs

2023-08-16 18:33 UTC, kcords requested changes
Looks great Josh! Just a few comments to address. Also, your build is failing, so you will probably need to look at those issues to correct the formatting errors before you can merge.

<img width="766" alt="Screenshot 2023-08-16 at 11 10 16 AM" src="https://github.com/KJP-Industries/can-of-books-frontend/assets/70975298/f8c24e90-d6ac-477e-a6a7-45b38f4c2573">

2023-08-16 18:33 UTC, kcords commented on src/components/BestBooks.js
> +    console.log('button test');
Let's remove this `console.log` before we merge unless there's a reason to leave it in prod.

2023-08-16 18:33 UTC, kcords commented on src/components/BestBooks.js
> +  };
We should ideally stay consistent here and use `.then`/`.catch`chaining here like we did in `componentDidMount`, otherwise we should change that method to an `async` function with `try`/`catch`.

2023-08-16 18:33 UTC, kcords commented on src/components/NewButton.js
> +export default NewButton;
This is great for now, but we can probably refactor this later to generalize it to make it reusable for use in multiple capacities (`create`, `update` and `delete`).

2023-08-16 20:18 UTC, easleyjs commented on src/components/BestBooks.js
> +    console.log('button test');
Removed!

2023-08-16 20:23 UTC, easleyjs commented on src/components/BestBooks.js
> +  };
Agree, looks good as just axios -> chained methods. Changed it over, and throwing errors to console.log, let me know if you think they should be going elsewhere

2023-08-16 20:24 UTC, easleyjs commented on src/components/NewButton.js
> +export default NewButton;
Yup, definitely. Leaving it "NewButton" for now.

2023-08-16 20:35 UTC, kcords requested changes

2023-08-16 20:35 UTC, kcords commented on src/components/BestBooks.js
> +  addBook = async (newBook) => {
One last thing... we can remove the async here since we aren't awaiting anything now

2023-08-16 20:35 UTC, kcords commented on src/components/BestBooks.js
> +              <Carousel.Item key={book._id}>
Great job on changing the `key` to `_id`! This is far more ideal.

2023-08-16 20:39 UTC, kcords commented on src/components/BestBooks.js
> +      .catch((err) => console.error(err));
Typically we wouldn't want to clutter the client console, but this is fine for now. Typically on the client, we'll want to surface the error to the user so they know what is going on. I can add something in our PR for displaying the error though.

2023-08-17 01:19 UTC, kcords approved these changes

2023-08-17 01:23 UTC, merged